CREATE TABLE [dbo].vaccines_city
(
	[_date] DATETIME NOT NULL, 
    [cityName] INT NOT NULL,
	[first_dose_0-19] INT NOT NULL, 
    [first_dose_20-29] INT NOT NULL, 
    [first_dose_30-39] INT NOT NULL, 
    [first_dose_40-49] INT NOT NULL, 
    [first_dose_50-59] INT NOT NULL, 
    [first_dose_60-69] INT NOT NULL, 
    [first_dose_70-79] INT NOT NULL, 
    [first_dose_80-89] INT NOT NULL, 
    [first_dose_90+] INT NOT NULL, 
	[second_dose_0-19] INT NOT NULL, 
    [second_dose_20-29] INT NOT NULL, 
    [second_dose_30-39] INT NOT NULL, 
    [second_dose_40-49] INT NOT NULL, 
    [second_dose_50-59] INT NOT NULL, 
    [second_dose_60-69] INT NOT NULL, 
    [second_dose_70-79] INT NOT NULL, 
    [second_dose_80-89] INT NOT NULL, 
    [second_dose_90+] INT NOT NULL, 
    primary key (cityName, _date),
)
